"""Initial database schema

Revision ID: 4d0d9a7c8308
Revises: 
Create Date: 2026-09-15 14:39:43.239298+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d0d9a7c8308'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('exam_name', sa.String(length=200), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('exam_shift', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('mock_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('negative_marking', sa.Float(), nullable=False),
    sa.Column('marks_per_correct', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("difficulty IN ('EASY', 'MEDIUM', 'HARD', 'MIXED')", name='ck_mock_tests_difficulty'),
    sa.CheckConstraint("source_type IN ('PYQ', 'AI_GENERATED', 'REFERENCE', 'MIXED')", name='ck_mock_tests_source_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mock_tests_user_id', 'mock_tests', ['user_id'], unique=False)
    op.create_table('pdf_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('exam_name', sa.String(length=200), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('exam_shift', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('questions_extracted', sa.Integer(), nullable=False),
    sa.Column('questions_stored', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_pdf_documents_user_id', 'pdf_documents', ['user_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'name', name='uq_topic_subject_name')
    )
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mock_test_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'EXPIRED')", name='ck_attempts_status'),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_mock_test_id', 'attempts', ['mock_test_id'], unique=False)
    op.create_index('ix_attempts_status', 'attempts', ['status'], unique=False)
    op.create_index('ix_attempts_user_id', 'attempts', ['user_id'], unique=False)
    op.create_table('pdf_processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pdf_document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED','PROCESSING','EXTRACTING','OCR','PARSING','VALIDATING','COMPLETED','FAILED')", name='ck_pdf_jobs_status'),
    sa.ForeignKeyConstraint(['pdf_document_id'], ['pdf_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pdf_jobs_pdf_document_id', 'pdf_processing_jobs', ['pdf_document_id'], unique=False)
    op.create_index('ix_pdf_jobs_status', 'pdf_processing_jobs', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('subtopic', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_exam', sa.String(length=200), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('answer_mapping_confidence', sa.Float(), nullable=True),
    sa.Column('pdf_document_id', sa.UUID(), nullable=True),
    sa.Column('pdf_page_number', sa.Integer(), nullable=True),
    sa.Column('question_number_in_source', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("correct_answer IN ('A', 'B', 'C', 'D')", name='ck_questions_correct_answer'),
    sa.CheckConstraint("difficulty IN ('EASY', 'MEDIUM', 'HARD')", name='ck_questions_difficulty'),
    sa.CheckConstraint("language IN ('ENGLISH', 'HINDI', 'BILINGUAL')", name='ck_questions_language'),
    sa.CheckConstraint("source_type IN ('PYQ', 'AI_GENERATED', 'REFERENCE')", name='ck_questions_source_type'),
    sa.CheckConstraint("verification_status IN ('VERIFIED', 'NEEDS_REVIEW', 'REJECTED', 'UNVERIFIED')", name='ck_questions_verification_status'),
    sa.ForeignKeyConstraint(['pdf_document_id'], ['pdf_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['question_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_pdf_document_id'), 'questions', ['pdf_document_id'], unique=False)
    op.create_index(op.f('ix_questions_source_id'), 'questions', ['source_id'], unique=False)
    op.create_index('ix_questions_source_type', 'questions', ['source_type'], unique=False)
    op.create_index('ix_questions_source_year', 'questions', ['source_year'], unique=False)
    op.create_index('ix_questions_subject_id', 'questions', ['subject_id'], unique=False)
    op.create_index('ix_questions_subject_topic_difficulty', 'questions', ['subject_id', 'topic_id', 'difficulty'], unique=False)
    op.create_index('ix_questions_topic_id', 'questions', ['topic_id'], unique=False)
    op.create_index('ix_questions_verification_status', 'questions', ['verification_status'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=True),
    sa.Column('is_marked', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("selected_answer IS NULL OR selected_answer IN ('A', 'B', 'C', 'D')", name='ck_attempt_answers_selected_answer'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_answers_attempt_question')
    )
    op.create_index('ix_attempt_answers_attempt_id', 'attempt_answers', ['attempt_id'], unique=False)
    op.create_table('mistake_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_mistake_user_question')
    )
    op.create_index(op.f('ix_mistake_questions_attempt_id'), 'mistake_questions', ['attempt_id'], unique=False)
    op.create_index('ix_mistake_questions_user_id', 'mistake_questions', ['user_id'], unique=False)
    op.create_table('mock_test_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mock_test_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_test_id', 'position', name='uq_mtq_mock_test_position'),
    sa.UniqueConstraint('mock_test_id', 'question_id', name='uq_mtq_mock_test_question')
    )
    op.create_index('ix_mock_test_questions_mock_test_id', 'mock_test_questions', ['mock_test_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mock_test_id', sa.UUID(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('unanswered', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('subject_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index('ix_results_mock_test_id', 'results', ['mock_test_id'], unique=False)
    op.create_index('ix_results_user_id', 'results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_results_user_id', table_name='results')
    op.drop_index('ix_results_mock_test_id', table_name='results')
    op.drop_table('results')
    op.drop_index('ix_mock_test_questions_mock_test_id', table_name='mock_test_questions')
    op.drop_table('mock_test_questions')
    op.drop_index('ix_mistake_questions_user_id', table_name='mistake_questions')
    op.drop_index(op.f('ix_mistake_questions_attempt_id'), table_name='mistake_questions')
    op.drop_table('mistake_questions')
    op.drop_index('ix_attempt_answers_attempt_id', table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index('ix_questions_verification_status', table_name='questions')
    op.drop_index('ix_questions_topic_id', table_name='questions')
    op.drop_index('ix_questions_subject_topic_difficulty', table_name='questions')
    op.drop_index('ix_questions_subject_id', table_name='questions')
    op.drop_index('ix_questions_source_year', table_name='questions')
    op.drop_index('ix_questions_source_type', table_name='questions')
    op.drop_index(op.f('ix_questions_source_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_pdf_document_id'), table_name='questions')
    op.drop_index('ix_questions_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_pdf_jobs_status', table_name='pdf_processing_jobs')
    op.drop_index('ix_pdf_jobs_pdf_document_id', table_name='pdf_processing_jobs')
    op.drop_table('pdf_processing_jobs')
    op.drop_index('ix_attempts_user_id', table_name='attempts')
    op.drop_index('ix_attempts_status', table_name='attempts')
    op.drop_index('ix_attempts_mock_test_id', table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_pdf_documents_user_id', table_name='pdf_documents')
    op.drop_table('pdf_documents')
    op.drop_index('ix_mock_tests_user_id', table_name='mock_tests')
    op.drop_table('mock_tests')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('question_sources')
    # ### end Alembic commands ###
